import Head from "next/head";
import Main from "../components/Main";
import Context from "../context/Context";

export default function Home() {
  return (
    <Context>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </Context>
  );
}
