import Head from "next/head";
import dynamic from "next/dynamic";
import Context from "../context/Context";
const DynamicComponent = dynamic(() => import("../components/Main"));

export default function Home() {
  return (
    <Context>
      <Head>
        <title>Case Converter PRO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DynamicComponent />
    </Context>
  );
}
